.PHONY : test

test: minicalc
        ./run-tests


minicalc: minicalc.c
        gcc -Wall -o minicalc minicalc.c -lm


stringbuilder: stringbuilder.h stringbuilder.c
        gcc -Wall -o stringbuilder stringbuilder.c